### ISSUE TITLE
environment.yaml dependency incompatibility

### ISSUE THREAD

**Issue by hhalcomb** [dhlab-epfl/dhSegment-torch#14]
Hi y'all. If I try to use the environment.yml in Ubuntu 22.04 as described, I get a dependency error:

`LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested numpy 1.21.0**
  - nothing provides requested tensorboard 2.4.1**
  - package pandas-1.3.2-py37h8c16a72_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy 1.21.0**  does not exist (perhaps a typo or a missing channel);
├─ pandas 1.3.2**  is installable with the potential options
│  ├─ pandas 1.3.2 would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ pandas 1.3.2 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ pandas 1.3.2 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
├─ python 3.10.11**  is not installable because it conflicts with any installable versions previously reported;
└─ tensorboard 2.4.1**  does not exist (perhaps a typo or a missing channel).`

If I try Anaconda in Windows instead, I get a similar error:
`ResolvePackageNotFound: 
- numpy=1.21.0
- tensorboard=2.4.1`

**Comment by alexislitvine** [comment]
Same issue here @hhalcomb - have you found a solution? @RPetitpierre - any suggestion?

**Comment by alexislitvine** [comment]
It seems to work by downgrading to Python 3.8 in the Yaml file
